#!/bin/bash
set -euo pipefail

# ntfy Mac PC 通知受信セットアップスクリプト
# Mac の通知センターで ntfy.sh の通知を受信するための環境を構築する

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/backend/.env"

PLIST_LABEL="sh.ntfy.subscriber"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_LABEL.plist"
CONFIG_DIR="$HOME/Library/Application Support/ntfy"
CONFIG_FILE="$CONFIG_DIR/client.yml"
LOG_FILE="/tmp/ntfy-subscriber.log"

echo "=== ntfy Mac 通知セットアップ ==="
echo ""

# 1. ntfy CLI のインストール確認
NTFY_PATH=$(which ntfy 2>/dev/null || true)
if [ -z "$NTFY_PATH" ]; then
    echo "[ERROR] ntfy CLI がインストールされていません。"
    echo ""
    echo "  以下のコマンドでインストールしてください:"
    echo "    brew install ntfy"
    echo ""
    exit 1
fi
echo "[OK] ntfy CLI: $NTFY_PATH"

# 2. NTFY_TOPIC の読み取り
if [ ! -f "$ENV_FILE" ]; then
    echo "[ERROR] backend/.env が見つかりません: $ENV_FILE"
    exit 1
fi

NTFY_TOPIC=$(grep '^NTFY_TOPIC=' "$ENV_FILE" | cut -d'=' -f2 | tr -d '[:space:]')
if [ -z "$NTFY_TOPIC" ]; then
    echo "[ERROR] backend/.env に NTFY_TOPIC が設定されていません。"
    echo ""
    echo "  backend/.env に以下を追加してください:"
    echo "    NTFY_TOPIC=your-unique-topic-name"
    echo ""
    exit 1
fi
echo "[OK] NTFY_TOPIC: $NTFY_TOPIC"

# 3. 設定ディレクトリの作成
mkdir -p "$CONFIG_DIR"
echo "[OK] 設定ディレクトリ: $CONFIG_DIR"

# 4. client.yml の生成
cat > "$CONFIG_FILE" << YAML
# ntfy client configuration
# Auto-generated by setup-ntfy.sh

default-host: https://ntfy.sh

subscribe:
  - topic: $NTFY_TOPIC
    command: |
      if command -v terminal-notifier >/dev/null 2>&1; then
        terminal-notifier -title "\$NTFY_TITLE" -message "\$NTFY_MESSAGE" -sound default
      else
        osascript -e "display notification \"\$NTFY_MESSAGE\" with title \"\$NTFY_TITLE\" sound name \"default\""
      fi
YAML
echo "[OK] 設定ファイル生成: $CONFIG_FILE"

# 5. LaunchAgent plist の生成
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$NTFY_PATH</string>
        <string>subscribe</string>
        <string>--from-config</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>
</dict>
</plist>
PLIST
echo "[OK] LaunchAgent 生成: $PLIST_PATH"

# 6. LaunchAgent の登録・起動
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"
echo "[OK] LaunchAgent を登録・起動しました"

# 7. テスト通知の送信
echo ""
echo "3秒待機後にテスト通知を送信します..."
sleep 3

curl -s \
    -H "Title: Ghostrunner" \
    -d "ntfy セットアップ完了! 通知が届いていれば成功です。" \
    "https://ntfy.sh/$NTFY_TOPIC" > /dev/null

echo "[OK] テスト通知を送信しました"

# 8. 確認案内
echo ""
echo "=== セットアップ完了 ==="
echo ""
echo "Mac の通知センターにテスト通知が届いていれば成功です。"
echo ""
echo "状態確認: make status-ntfy"
echo "アンインストール: make uninstall-ntfy"

# 9. トラブルシューティング
echo ""
echo "--- 通知が届かない場合 ---"
echo "1. システム設定 > 通知 で terminal-notifier または Script Editor の通知が許可されているか確認"
echo "2. make status-ntfy でプロセスとログを確認"
echo "3. ログファイル: $LOG_FILE"
echo "4. 手動テスト: curl -d 'test' https://ntfy.sh/$NTFY_TOPIC"
